spring:
    application:
        name: journalapp
    data:
        mongodb:
            uri: ${mongokey}
            database: journaldb
            auto-index-creation: true
        redis:
            host: localhost
            port: 6379
    config:
        import: optional:file:.env[.properties]
    security:
        user:
            name: admin
            password: admin123
            roles: USER
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${email-id}
        password: ${gmail-password}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
server:
  port: 5050

