spring:
    application:
        name: journalapp
    data:
        mongodb:
            uri: ${mongokey}
            database: journaldb
            auto-index-creation: true
    config:
        import: optional:file:.env[.properties]
    security:
        user:
            name: admin
            password: admin123
            roles: USER
server:
  port: 5050